Fix compilation error: Use GxEPD2_420c_Z21 instead of non-existent GxEPD2_420_Z15
- GxEPD2_420_Z15 doesn't exist in the library
- Switch to GxEPD2_420c_Z21 (UC8176 controller)
- Update debug output